---
core:
    num_workers: 100

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/inventory/hosts.yaml"
        group_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/inventory/groups.yaml"
        defaults_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/inventory/defaults.yaml"