---
core:
    num_workers: 100

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/hardening_check/hosts.yaml"
        group_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/hardening_check/groups.yaml"
        defaults_file: "C:/Users/aabdurahmanov/Network_Automation/Nornir/hardening_check/defaults.yaml"